---
- name: Install Java
  hosts: all
  gather_facts: false
  become: yes

  tasks:
  - name: Update system
    command: yum -y update

  - name: install java
    yum:
      name:  java
      state: present

  - name: Copy APP service from local to remote
    copy:
       src: spring.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: Start and enable APP service
    systemd:
      name: spring
      state: started

  - name: enable APP
    systemd:
      name: spring
      enabled: true
